import { Project, Table, Field, Relationship } from '../types';

// JSON 내보내기 (현재 구조 그대로)
export const exportToJSON = (project: Project): string => {
  const exportData = {
    ...project,
    exportedAt: new Date().toISOString(),
    version: '1.0'
  };
  return JSON.stringify(exportData, null, 2);
};

// DBML 내보내기
export const exportToDBML = (project: Project): string => {
  const lines: string[] = [];
  
  // 프로젝트 정보
  lines.push(`// Project: ${project.name}`);
  lines.push(`// Database: ${project.db_type}`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push('');

  // 테이블 정의
  project.tables.forEach(table => {
    let tableLine = `Table ${table.name}`;
    if (table.comment) {
      tableLine += ` [note: '${table.comment}']`;
    }
    tableLine += ' {';
    lines.push(tableLine);
    
    table.fields.forEach(field => {
      let fieldLine = `  ${field.name} ${field.type}`;
      
      const attributes: string[] = [];
      if (field.isPrimaryKey) attributes.push('pk');
      if (field.isRequired) attributes.push('not null');
      if (field.isUnique) attributes.push('unique');
      if (field.isAutoIncrement) attributes.push('increment');
      if (field.defaultValue) attributes.push(`default: '${field.defaultValue}'`);
      if (field.isForeignKey) attributes.push(`ref: > ${field.referencedTable}.${field.referencedField}`);
      if (field.comment) attributes.push(`note: '${field.comment}'`);
      
      if (attributes.length > 0) {
        fieldLine += ` [${attributes.join(', ')}]`;
      }
      
      lines.push(fieldLine);
    });

    // 인덱스 정의
    if (table.indexes && table.indexes.length > 0) {
      lines.push('');
      table.indexes.forEach(index => {
        const indexType = index.type === 'PRIMARY' ? '' : index.type.toLowerCase();
        const fields = index.fields.join(', ');
        if (indexType) {
          lines.push(`  Indexes {`);
          lines.push(`    ${index.name} [type: ${indexType}] (${fields})`);
          lines.push(`  }`);
        } else {
          lines.push(`  Indexes {`);
          lines.push(`    ${index.name} (${fields})`);
          lines.push(`  }`);
        }
      });
    }
    
    lines.push('}');
    lines.push('');
  });

  // 관계 정의 (Foreign Key가 아닌 별도 관계)
  const separateRefs = project.relationships.filter(rel => 
    !project.tables.some(table => 
      table.fields.some(field => 
        field.isForeignKey && 
        field.referencedTable === rel.fromTable && 
        field.referencedField === rel.fromField
      )
    )
  );

  if (separateRefs.length > 0) {
    lines.push('// Relationships');
    separateRefs.forEach(rel => {
      const refType = getDBMLRefType(rel.type);
      lines.push(`Ref: ${rel.fromTable}.${rel.fromField} ${refType} ${rel.toTable}.${rel.toField}`);
    });
  }

  return lines.join('\n');
};

// SQL 내보내기
export const exportToSQL = (project: Project): string => {
  const lines: string[] = [];
  
  lines.push(`-- Project: ${project.name}`);
  lines.push(`-- Database: ${project.db_type}`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push('');

  // 테이블 생성
  project.tables.forEach(table => {
    let createTableSQL = `CREATE TABLE ${table.name} (`;
    if (table.comment) {
      // 테이블 코멘트는 테이블 생성 후에 추가됩니다
    }
    lines.push(createTableSQL);
    
    const fieldLines = table.fields.map(field => {
      let fieldDef = `  ${field.name} ${field.type}`;
      
      if (field.isAutoIncrement) {
        if (project.db_type === 'mysql') {
          fieldDef += ' AUTO_INCREMENT';
        } else if (project.db_type === 'postgresql') {
          // PostgreSQL의 경우 SERIAL 타입 사용을 권장하지만, 여기서는 명시적으로 처리
          fieldDef += ' GENERATED BY DEFAULT AS IDENTITY';
        }
      }
      
      if (field.isRequired) fieldDef += ' NOT NULL';
      if (field.isPrimaryKey) fieldDef += ' PRIMARY KEY';
      if (field.isUnique && !field.isPrimaryKey) fieldDef += ' UNIQUE';
      
      if (field.defaultValue && !field.isAutoIncrement) {
        fieldDef += ` DEFAULT '${field.defaultValue}'`;
      }
      
      if (field.checkConstraint) {
        fieldDef += ` CHECK (${field.checkConstraint})`;
      }
      
      if (field.comment) {
        fieldDef += ` COMMENT '${field.comment}'`;
      }
      
      return fieldDef;
    });
    
    lines.push(fieldLines.join(',\n'));
    lines.push(')');
    
    // 테이블 코멘트 추가
    if (table.comment) {
      lines[lines.length - 1] += ` COMMENT='${table.comment}'`;
    }
    
    lines[lines.length - 1] += ';';
    lines.push('');
  });

  // 인덱스 생성
  const indexes = project.tables.flatMap(table =>
    (table.indexes || []).map(index => ({
      tableName: table.name,
      indexName: index.name,
      fields: index.fields,
      type: index.type,
      method: index.method
    }))
  );

  if (indexes.length > 0) {
    lines.push('-- Indexes');
    indexes.forEach(idx => {
      let indexSQL = `CREATE`;
      
      if (idx.type === 'UNIQUE') {
        indexSQL += ` UNIQUE`;
      } else if (idx.type === 'FULLTEXT') {
        indexSQL += ` FULLTEXT`;
      }
      
      indexSQL += ` INDEX ${idx.indexName} ON ${idx.tableName}`;
      
      if (idx.method && idx.method !== 'BTREE') {
        indexSQL += ` USING ${idx.method}`;
      }
      
      indexSQL += ` (${idx.fields.join(', ')});`;
      lines.push(indexSQL);
    });
    lines.push('');
  }

  // Foreign Key 제약조건
  const foreignKeys = project.tables.flatMap(table =>
    table.fields
      .filter(field => field.isForeignKey)
      .map(field => ({
        table: table.name,
        field: field.name,
        referencedTable: field.referencedTable!,
        referencedField: field.referencedField!
      }))
  );

  if (foreignKeys.length > 0) {
    lines.push('-- Foreign Key Constraints');
    foreignKeys.forEach(fk => {
      lines.push(
        `ALTER TABLE ${fk.table} ADD CONSTRAINT fk_${fk.table}_${fk.field} ` +
        `FOREIGN KEY (${fk.field}) REFERENCES ${fk.referencedTable}(${fk.referencedField});`
      );
    });
  }

  return lines.join('\n');
};

// DBML에서 가져오기 (기본 파싱)
export const importFromDBML = (dbmlContent: string): Partial<Project> => {
  const tables: Table[] = [];
  const relationships: Relationship[] = [];
  
  const lines = dbmlContent.split('\n').map(line => line.trim());
  let currentTable: Table | null = null;
  let tableIdCounter = 1;
  let relIdCounter = 1;
  let indexIdCounter = 1;
  let inIndexSection = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    // 테이블 시작
    if (line.startsWith('Table ') && line.includes('{')) {
      const tableMatch = line.match(/Table\s+(\w+)(?:\s*\[([^\]]+)\])?/);
      if (tableMatch) {
        const [, tableName, tableAttributes] = tableMatch;
        currentTable = {
          id: `t${tableIdCounter++}`,
          name: tableName,
          fields: [],
          indexes: [],
          position: { x: Math.random() * 300 + 50, y: Math.random() * 200 + 100 }
        };
        
        // 테이블 속성 파싱 (note 등)
        if (tableAttributes) {
          const noteMatch = tableAttributes.match(/note:\s*['"]([^'"]+)['"]/);
          if (noteMatch) {
            currentTable.comment = noteMatch[1];
          }
        }
      }
      inIndexSection = false;
    }
    
    // 인덱스 섹션 시작
    else if (currentTable && line === 'Indexes {') {
      inIndexSection = true;
    }
    
    // 인덱스 섹션 끝
    else if (inIndexSection && line === '}' && !line.startsWith('Table')) {
      inIndexSection = false;
    }
    
    // 테이블 끝
    else if (line === '}' && currentTable && !inIndexSection) {
      tables.push(currentTable);
      currentTable = null;
    }
    
    // 인덱스 정의
    else if (inIndexSection && currentTable && line && !line.startsWith('//')) {
      const indexMatch = line.match(/(\w+)(?:\s*\[type:\s*(\w+)\])?\s*\(([^)]+)\)/);
      if (indexMatch) {
        const [, name, type, fields] = indexMatch;
        
        const index = {
          id: `idx${indexIdCounter++}`,
          name: name.trim(),
          fields: fields.split(',').map(f => f.trim()),
          type: (type ? type.toUpperCase() : 'INDEX') as 'INDEX' | 'UNIQUE' | 'FULLTEXT' | 'PRIMARY'
        };
        
        currentTable.indexes!.push(index);
      }
    }
    
    // 필드 정의
    else if (currentTable && line && !line.startsWith('//') && !inIndexSection) {
      const fieldMatch = line.match(/(\w+)\s+([^\[]+)(?:\[([^\]]+)\])?/);
      if (fieldMatch) {
        const [, name, type, attributes] = fieldMatch;
        
        const field: Field = {
          name: name.trim(),
          type: type.trim(),
          isPrimaryKey: false,
          isRequired: false
        };
        
        if (attributes) {
          field.isPrimaryKey = attributes.includes('pk');
          field.isRequired = attributes.includes('not null');
          field.isUnique = attributes.includes('unique');
          field.isAutoIncrement = attributes.includes('increment');
          
          // 기본값 파싱
          const defaultMatch = attributes.match(/default:\s*['"]([^'"]+)['"]/);
          if (defaultMatch) {
            field.defaultValue = defaultMatch[1];
          }
          
          // 코멘트 파싱
          const noteMatch = attributes.match(/note:\s*['"]([^'"]+)['"]/);
          if (noteMatch) {
            field.comment = noteMatch[1];
          }
          
          // 외래키 참조 파싱
          const refMatch = attributes.match(/ref:\s*>\s*(\w+)\.(\w+)/);
          if (refMatch) {
            field.isForeignKey = true;
            field.referencedTable = refMatch[1];
            field.referencedField = refMatch[2];
          }
        }
        
        currentTable.fields.push(field);
      }
    }
    
    // 별도 관계 정의
    else if (line.startsWith('Ref:')) {
      const refMatch = line.match(/Ref:\s*(\w+)\.(\w+)\s*([<>-]+)\s*(\w+)\.(\w+)/);
      if (refMatch) {
        const [, fromTable, fromField, refType, toTable, toField] = refMatch;
        
        relationships.push({
          id: `r${relIdCounter++}`,
          fromTable,
          fromField, 
          toTable,
          toField,
          type: getRelationshipType(refType)
        });
      }
    }
  }

  return {
    tables,
    relationships,
    db_type: 'mysql' // 기본값
  };
};

// JSON에서 가져오기
export const importFromJSON = (jsonContent: string): Partial<Project> => {
  try {
    const data = JSON.parse(jsonContent);
    return {
      name: data.name,
      db_type: data.db_type || data.dbType || 'mysql',
      tables: data.tables || [],
      relationships: data.relationships || []
    };
  } catch (error) {
    throw new Error('Invalid JSON format');
  }
};

// 헬퍼 함수들
const getDBMLRefType = (relType: string): string => {
  switch (relType) {
    case '1:1': return '-';
    case '1:N': return '<';
    case 'N:1': return '>';
    case 'N:N': return '<>';
    default: return '-';
  }
};

const getRelationshipType = (refType: string): '1:1' | '1:N' | 'N:1' | 'N:N' | '0:1' | '1:0' => {
  switch (refType.trim()) {
    case '-': return '1:1';
    case '<': return '1:N';
    case '>': return 'N:1';
    case '<>': return 'N:N';
    default: return '1:N';
  }
};